# ---- Donation Rank Item ---- #
Item for Viewing:
  ==: org.bukkit.inventory.ItemStack
  type: BOOK
  amount: 1
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: Ye Olde Donation Ranks
    enchants:
      PROTECTION_ENVIRONMENTAL: 1
    repair-cost: 2